/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_URL?.split('https://')[1]?.split('.supabase.co')[0] || 'gjpfldimavnqthuqdqbe'
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqcGZsZGltYXZucXRodXFkcWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2NTE5NjUsImV4cCI6MjA4MTIyNzk2NX0.6YdLpyQwoTXmGl70afKwBcQqXKSAmigRyDYxBD0gZH4'